version: '2'

services:
   samba:
    container_name: samba
    ports:
      - '137-139:137-139'
      - '6699:6699'
      - '445:445'
    image: vulnerables/cve-2017-7494
    restart: always
    tty: true
   falco:
    container_name: falco
    image: sysdig/falco:latest
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - ${PWD}/falco_rules.yaml:/etc/falco/falco_rules.yaml
      - ${PWD}/falco_rules.local.yaml:/etc/falco/falco_rules.local.yaml
    tty: true
